const USER_ACTION_TYPES = {
  USER_LOGIN_SUCCESS: "user/USER_LOGIN_SUCCESS",
  USER_LOGIN_REQUEST: "user/USER_LOGIN_START",
  USER_LOGIN_FAILED: "user/USER_LOGIN_FAILED",
  USER_REGISTER_SUCCESS: "user/USER_REGISTER_SUCCESS",
  USER_REGISTER_REQUEST: "user/USER_REGISTER_REQUEST",
  USER_REGISTER_FAILED: "user/USER_REGISTER_FAILED",
  LOAD_USER_DATA_REQUEST: "user/LOAD_USER_DATA_REQUEST",
  LOAD_USER_DATA_SUCCESS: "user/LOAD_USER_DATA_SUCCESS",
  LOAD_USER_DATA_FAILED: "user/LOAD_USER_DATA_FAILED",
  USER_LOGOUT_SUCCESS: "user/USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILED: "user/USER_LOGOUT_FAILED",
};

export default USER_ACTION_TYPES;
