const BOARD_ACTION_TYPES = {
  FETCH_BOARDS_START: "board/FETCH_BOARDS_START",
  FETCH_BOARDS_SUCCESS: "board/FETCH_BOARDS_SUCCESS",
  FETCH_BOARDS_FAILED: "board/FETCH_BOARDS_FAILED",
  DELETE_BOARD_START: "board/DELETE_BOARD_START",
  DELETE_BOARD_SUCCESS: "board/DELETE_BOARD_SUCCESS",
  DELETE_BOARD_FAILED: "board/DELETE_BOARD_FAILED",
  SET_CURRENT_BOARD: "board/SET_CURRENT_BOARD",
  LOAD_CURRENT_BOARD: "board/LOAD_CURRENT_BOARD",
  ERROR_CURRENT_BOARD: "board/ERROR_CURRENT_BOARD",
};

export default BOARD_ACTION_TYPES;
