const UI_ACTION_TYPES = {
  UI_THEME_MODE: "ui/UI_THEME_MODE",
  UI_SIDEBAR_TOGGLE: "ui/UI_SIDEBAR_TOGGLE",
  UI_BOARD_FORM_TOGGLE: "ui/UI_BOARD_FORM_TOGGLE",
  UI_COLUMN_FORM_TOGGLE: "ui/UI_COLUMN_FORM_TOGGLE",
  UI_DELETE_BOARD_FORM_TOGGLE: "ui/UI_DELETE_BOARD_FORM_TOGGLE",
};

export default UI_ACTION_TYPES;
