const TASK_ACTION_TYPE = {
  CREATE_TASK_SUCCESS: "task/CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILED: "task/CREATE_TASK_FAILED",
  SELECT_TASK_LOADING: "task/SELECT_TASK_LOADING",
  SELECT_TASK_SUCCESS: "task/SELECT_TASK_SUCCESS",
  SELECT_TASK_FAILED: "task/SELECT_TASK_FAILED",
  UPDATE_TASK_LOADING: "task/UPDATE_TASK_LOADING",
  UPDATE_TASK_SUCCESS: "task/UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILED: "task/UPDATE_TASK_FAILED",
  DELETE_TASK_SUCCESS: "task/DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILED: "task/DELETE_TASK_FAILED",
};

export default TASK_ACTION_TYPE;
