//* USER ACTION TYPES */

const USER_ACTION_TYPES = {
  USER_LOGIN_START: "user/USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "user/USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "user/USER_LOGIN_FAILED",
  USER_LOGOUT_START: "user/USER_LOGOUT_START",
  USER_LOGOUT_SUCCESS: "user/USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILED: "user/USER_LOGOUT_FAILED",
  USER_REGISTER_START: "user/USER_REGISTER_START",
  USER_REGISTER_SUCCESS: "user/USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILED: "user/USER_REGISTER_FAILED",
};

export default USER_ACTION_TYPES;
